name = "Math 3345H"
version = "1.0.0"
extra_files = "extras"
intro = "src/math3345h/intro.lean"

[[worlds]]
name = "Propositions"
id = 1
levels = [
	"src/propositions/level1.lean",
	"src/propositions/level2.lean",
	"src/propositions/level3.lean"
]
